
[env:esp32dev]
platform = espressif32@5.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200

; upload_protocol = espota
; upload_port = 192.168.7.73

lib_deps =
    me-no-dev/ESPAsyncWebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1
    bblanchon/ArduinoJson@^7.4.2
    bogde/HX711@^0.7.5

